# backend/app/main.py
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import os

# Import the dynamic function launcher instead of static object instantiation
from app.agent import get_agent_instance

app = FastAPI(title="Google Drive AI Agent Backend")

# CORS Middleware for Frontend-Backend Communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://my-drive-ai-agent.streamlit.app"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request Schema Structure Mapping
class ChatRequest(BaseModel):
    message: str
    folder_id: Optional[str] = None

@app.post("/chat")
async def chat_endpoint(req: ChatRequest):
    # Dynamic check to ensure keys are populated on user request runtime
    if not os.getenv("GEMINI_API_KEY") and not os.getenv("GOOGLE_API_KEY"):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail="Backend configuration error: GEMINI_API_KEY is missing on Render environment."
        )
        
    try:
        # Pass folder scope parameter down safely into prompt injection structure
        target_folder = req.folder_id if req.folder_id and req.folder_id != "None" else "all_drive"
        
        # Call initialization safely at execution runtime frame (Prevents import-time validation crash)
        active_agent = get_agent_instance()
        
        # Invoke LangGraph/LangChain ReAct Agent
        response = active_agent.invoke({
            "messages": [("user", req.message)],
            "folder_id": target_folder
        })
        
        # Parse LangGraph state channels outputs
        output_messages = response.get("messages", [])
        if output_messages:
            final_reply = output_messages[-1].content
            return {"response": final_reply}
            
        return {"response": response.get("output", "No response generated by core agent loops.")}
        
    except Exception as e:
        error_msg = str(e)
        # Check for Gemini 429 Quota/Rate Limit Exhaustion
        if "429" in error_msg or "RESOURCE_EXHAUSTED" in error_msg:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail="Gemini Rate Limit Exceeded. Please try again in 60 seconds."
            )
        # Fallback for all other internal errors
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=error_msg)

@app.get("/folders")
async def folders_endpoint():
    from app.tools import get_all_folders
    try:
        folders = get_all_folders()
        return {"folders": folders}
    except Exception as e:
        # Return elegant empty list fallback context if API breaks down
        return {"folders": []}