# backend/app/main.py
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import os

# Import the dynamic function launcher instead of static object instantiation
from app.agent import get_agent_instance

app = FastAPI(title="Google Drive AI Agent Backend")

# CORS Middleware for Frontend-Backend Communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://drive-power-ai-agent.streamlit.app/"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request Schema Structure Mapping
class ChatRequest(BaseModel):
    message: str
    folder_id: Optional[str] = None

@app.post("/chat")
async def chat_endpoint(req: ChatRequest):
    # 🔑 Dynamic check to ensure keys are populated on user request runtime without crashing the process
    if not os.getenv("GEMINI_API_KEY") and not os.getenv("GOOGLE_API_KEY"):
        return {"response": "⚠️ **Configuration Error**: API Key missing on Render environment setup."}
        
    try:
        # Pass folder scope parameter down safely into prompt injection structure
        target_folder = req.folder_id if req.folder_id and req.folder_id != "None" else "all_drive"
        
        # Call initialization safely at execution runtime frame (Prevents import-time validation crash)
        active_agent = get_agent_instance()
        
        # Invoke LangGraph/LangChain ReAct Agent
        response = active_agent.invoke({
            "messages": [("user", req.message)],
            "folder_id": target_folder
        })
        
        # 🎯 STRONGER PARSING FOR LANGGRAPH CONTENT CHANNELS (Prevents UI JSON string crashes)
        output_messages = response.get("messages", [])
        if output_messages:
            final_node = output_messages[-1]
            
            # Agar agent ka output ek standard LangChain object list matrix ya raw block list hai
            if isinstance(final_node.content, list):
                extracted_text = ""
                for block in final_node.content:
                    if isinstance(block, dict) and "text" in block:
                        extracted_text += block["text"]
                    elif hasattr(block, "get") and block.get("text"):
                        extracted_text += block.get("text")
                return {"response": extracted_text if extracted_text else str(final_node.content)}
                
            # Standard single string property backup fallback
            return {"response": final_node.content}
            
        # Fallback if messages key is missing but generic output channel exists
        return {"response": response.get("output", "No response generated by core agent loops.")}
        
    except Exception as e:
        error_msg = str(e)
        # Catch Gemini 429 Quota/Rate Limit Exhaustion and return as safe text dictionary instead of HTTP exception
        if "429" in error_msg or "RESOURCE_EXHAUSTED" in error_msg:
            return {"response": "⚠️ **Gemini API Rate Limit (429) Hit**: Free tier limits exceeded. Please wait 30-60 seconds before trying again."}
        
        # Fallback dictionary response for any other unexpected internal errors
        return {"response": f"⚠️ **Internal Backend Error**: {error_msg}"}

@app.get("/folders")
async def folders_endpoint():
    from app.tools import get_all_folders
    try:
        folders = get_all_folders()
        return {"folders": folders}
    except Exception as e:
        # Return elegant empty list fallback context if API breaks down
        return {"folders": []}